# Generated by Django 5.0.6 on 2024-06-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scartapp', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Name', models.CharField(max_length=200)),
                ('P_Type', models.CharField(max_length=200)),
                ('P_Model', models.CharField(max_length=50)),
                ('P_Meterial', models.CharField(max_length=200)),
                ('P_Description', models.CharField(max_length=200)),
                ('P_Image', models.FileField(default='default', upload_to='static/images/')),
                ('P_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('P_Size', models.CharField(max_length=5)),
                ('P_Color', models.CharField(max_length=50)),
                ('P_Qty', models.BigIntegerField()),
                ('P_Person', models.CharField(max_length=200)),
            ],
        ),
    ]
