# Generated by Django 5.0.6 on 2024-06-12 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scartapp', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scartapp.products')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scartapp.profile')),
            ],
        ),
    ]
