# Generated by Django 5.0.6 on 2024-06-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scartapp', '0005_cart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
